######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 16 11:32:53 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += plusminus.h
SOURCES += main.cpp plusminus.cpp
