######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 22 10:26:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += abstorel.cpp
