######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 22 12:43:55 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qlsp.cpp
