######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 22 12:33:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtversion.cpp
