######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 14 09:54:16 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
