######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 16 11:53:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += skeleton.h
SOURCES += main.cpp skeleton.cpp
