######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 15 16:55:39 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtextedit_pushbutton.cpp
